apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  project: default
  source:
    # Replace this placeholder with the Git remote URL for this repository.
    repoURL: https://github.com/jjyung/cloud-native-ops-lab.git
    targetRevision: main
    path: app/hello
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy: {}
